openapi: 3.0.3
info:
  title: /userSessions
  version: 0.0.0
paths:
  /userSessions:
    post:
      summary: Create a user session
      tags:
        - userSessions
      operationId: createUserSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../requests/UserSessionsRequest.yml'
      responses:
        '200':
          $ref: '../responses/UserSessionsResponse.yml'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      parameters:
        - schema:
            type: string
          in: header
          name: UID
          required: true
          description: |-
            Maybe any hex value is allowed. e.g. `a`.
      description: |-
        Login to the Resonite service and create a user session.
