openapi: 3.0.3
info:
  title: /users
  version: 0.0.0
paths:
  /users:
    get:
      summary: Search Users by username
      tags:
        - users
      operationId: searchUsers
      parameters:
        - $ref: '../parameters.yml#/name'
      responses:
        '200':
          $ref: '../responses/users/SearchUsersResponse.yml'
      description: |-
        Returns a list of users.
  /users/{userId}:
    get:
      summary: Get User by User ID
      tags:
        - users
      operationId: getUser
      parameters:
        - $ref: '../parameters.yml#/userId'
      responses:
        '200':
          $ref: '../responses/users/GetUserResponse.yml'
        '400':
          description: Invalid user ID
        '404':
          description: User not found
      description: |-
        Returns a single user.
  /users/{userId}/contacts:
    get:
      summary: Get User Contacts
      tags:
        - users
      operationId: getUserContacts
      security:
        - resAuth: []
      parameters:
        - $ref: '../parameters.yml#/userId'
      responses:
        '200':
          $ref: '../responses/users/GetUserContactsResponse.yml'
        '401':
          description: Unauthorized
      description: |-
        Retrieve the list of contacts for the user. Used to get your own contact list.
