# This file is based on vrchatapi/specification repository and is licensed under MIT.
# https://github.com/vrchatapi/specification/blob/main/.spectral.yaml

formats:
  - oas3

extends:
  - 'spectral:oas'

rules:
  oas3-parameter-description: info
  tag-description: hint

  # Rules for sub schema
  info-contact: off
  info-description: off
  info-license: off
  license-url: off
  oas3-api-servers: off

  schema-title:
    given: '$.components.schemas[*]'
    severity: error
    then:
      field: title
      function: truthy

  response-no-inline-schemas:
    given: '$.components.responses[*].content.application/json.schema.type'
    severity: error
    resolved: false
    then:
      function: pattern
      functionOptions:
        notMatch: 'object'

  paths-no-inline-responses:
    given: '$.paths[*][get,post,put,delete].responses[*].content.application/json.schema'
    severity: error
    resolved: false
    then:
      function: undefined

  paths-no-inline-requests:
    given: '$.paths[*][get,post,put,delete].requestBody.content.application/json.schema.properties'
    severity: error
    resolved: false
    then:
      function: undefined
