includeEmptyHeadless:
  name: includeEmptyHeadless
  in: query
  schema:
    type: boolean
  description: Include empty headless sessions
minActiveUsers:
  name: minActiveUsers
  in: query
  schema:
    type: number
  description: Minimum number of active users
sessionId:
  name: sessionId
  in: path
  required: true
  schema:
    type: string
  description: The session ID
userId:
  name: userId
  in: path
  required: true
  schema:
    type: string
  description: The user ID. Should start with `U-`.
  example: 'U-Eai'
name:
  name: name
  in: query
  schema:
    type: string
  description: The username to search.
  example: 'Eai'
